repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      - id: ruff-format
        name: Ruff formater
        stages: [pre-commit]
      - id: ruff
        name: Ruff linter
        args: [ --fix ]
        stages: [pre-commit]

  - repo: local
    hooks:
    - id: tests
      name: Tests
      entry: uv run pytest
      pass_filenames: false
      language: system
      stages: [pre-push]