repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        name: Ruff linter
        args: [ --fix ]
        stages: [commit]
      - id: ruff-format
        name: Ruff formater
        stages: [commit]

  - repo: local
    hooks:
    - id: empty-label-cache
      name: Empty Label Cache
      entry: python empty_label_cache.py
      language: system
      stages: [commit]
    - id: tests
      name: Tests
      entry: pytest
      pass_filenames: false
      language: system
      stages: [push] # for it to work, run: pre-commit install --hook-type pre-commit --hook-type pre-push