repos:
  - repo: local
    hooks:
      - id: ruff-formatter
        name: Ruff formatter
        entry: uv run ruff format .
        pass_filenames: false
        language: system
        stages: [pre-commit]
      - id: ruff-linter
        name: Ruff linter
        entry: uv run ruff check . --fix
        pass_filenames: false
        language: system
        stages: [pre-commit]
      - id: mypy-type-checker
        name: Mypy type checker
        entry: uv run mypy . --strict
        pass_filenames: false
        language: system
        stages: [pre-commit]
      - id: check-lock
        name: Check lock up to date
        entry: uv lock --locked
        pass_filenames: false
        language: system
        stages: [pre-commit]
      - id: tests
        name: Tests
        entry: uv run pytest
        pass_filenames: false
        language: system
        stages: [pre-push]
      - id: tag-version-on-push
        name: Tag version on push if changed
        entry: ./tag_version.sh
        language: script
        stages: [pre-push]