[tool.poetry]
name = "stock-portfolio-tracker"
version = "0.1.0"
description = ""
authors = ["Llorenc Buil"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.2"
pandas = "^2.2.2"
yfinance = "^0.2.40"
pandas-datareader = "^0.10.0"
python-dotenv = "^1.0.1"
pre-commit = "^3.7.1"
ruff = "^0.4.6"
matplotlib = "^3.9.0"
loguru = "^0.7.2"

[tool.ruff]
line-length = 100
lint.select = [
    "F", "E", "W", "ARG", "C90", "I", "N", "D", "UP", "YTT", "ANN", "S", "BLE", "FBT", "B", "A",
    "COM", "C40", "DTZ", "T10", "DJ", "EXE", "ISC", "ICN", "G", "INP", "PIE", "T20", "PYI", "PT",
    "Q", "RSE", "RET", "SLF", "SIM", "TID", "TCH", "ARG", "PTH", "ERA", "PD", "PGH", "PL", "TRY",
    "NPY", "RUF"
]
lint.ignore = ["PD015", "PD901","ANN002", "ANN003", "TRY002", "TRY003", "BLE001"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
