[tool.poetry]
name = "stock-portfolio-tracker"
version = "0.1.0"
description = ""
authors = ["Llorenc Buil"]
readme = "README.md"

[tool.poetry.scripts]
stock-portfolio-tracker = "stock_portfolio_tracker.__main__:_main"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.2"
pandas = "^2.2.2"
yfinance = "^0.2.40"
pandas-datareader = "^0.10.0"
python-dotenv = "^1.0.1"
pre-commit = "^3.7.1"
ruff = "^0.4.6"
matplotlib = "^3.9.0"
loguru = "^0.7.2"
pytest = "^8.2.2"
click = "^8.1.7"

[tool.ruff]
line-length = 100
lint.select = ["ALL"]
lint.ignore = [
    "PD901", "ANN002", "ANN003", "TRY002", "TRY003", "BLE001", "PLR0913", "S101", "ANN401", "D205",
    "D402", "D203", "D213", "FA102"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
